### ISSUE TITLE
how to implement share feature in ionic

### ISSUE THREAD

**Issue by RS-Shekhawat** [ROKOLabs/ROKO.Mobi-Cordova#1]
Hi ROKOLabs support,

Could you please ellobrate the share feature implementation steps in cordova. Where we need to apply share link in the share section in ROKOLab. 
I have facing some issue in that, in my rokolab dashboard showing hits in share section but i can't identify how to  share

**Comment by sselin** [comment]
Hi, please take a look at https://docs.roko.mobi/docs/ionic-integration-guide, please ping help@rokolabs.com if you have any additional questions.
