### ISSUE TITLE
ReferralManager.java Build Error

### ISSUE THREAD

**Issue by brandecho** [ROKOLabs/ROKO.Mobi-Cordova#3]
Getting the following error in the Gradle Console when building apk: /platforms/android/src/com/rokolabs/rokomobi/referral/ReferralManager.java:228: error: method does not override or implement a method from a supertype
                            @Override

Error:  Method 'success(com.rokolabs.sdk.referrals.ResponseRedeemReferralDiscount)' is never used.
also:
Parameter 'responseRedeemReferralDiscount' is never used.

**Comment by jngnyc** [comment]
hey @brandecho. Thanks for reporting this. I'll escalate with our SDK team and get back to you shortly. Please standby.

**Comment by jngnyc** [comment]
Hi @brandecho - our SDK team was able to isolate the issue and we're working on rolling out a fix in the next few days. I'll update you as we go along. Thanks for your patience.

**Comment by brandecho** [comment]
Thank you very much for the update.

**Comment by jngnyc** [comment]
Hi @brandecho - our technical believes that you may be working with a slightly outdated version of the Cordova plugin. The latest version is v0.0.71.

**Can you try updating your Cordova plugin, do a clean build, and check if you're still encountering the issue?** 

(plugin update instructions - https://docs.roko.mobi/docs/faq-sdk-sdkversion#section-cordova)

**Comment by brandecho** [comment]
Hello. Version  v0.0.71. is what we are using.

**Comment by brandecho** [comment]
Hi @jngnyc We updated the plugin recently to your latest version v0.0.74 and all seems to be working well now. Thank you for the follow up.
